// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ML7NEoan03Vkk8cjl22PWzkCoGqOMWk',
    appId: '1:195208708595:web:02dbc7906c829052129286',
    messagingSenderId: '195208708595',
    projectId: 'appbook-1e0d2',
    authDomain: 'appbook-1e0d2.firebaseapp.com',
    databaseURL: 'https://appbook-1e0d2-default-rtdb.firebaseio.com',
    storageBucket: 'appbook-1e0d2.appspot.com',
    measurementId: 'G-H2E6RDQG84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nadJaUVp3_PTh-M5Eiwqh0RFBbcX45k',
    appId: '1:195208708595:android:6b06c17cf5cadc52129286',
    messagingSenderId: '195208708595',
    projectId: 'appbook-1e0d2',
    databaseURL: 'https://appbook-1e0d2-default-rtdb.firebaseio.com',
    storageBucket: 'appbook-1e0d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQrACd7hfauB_85IKYpZUWQtmUdDK-6hs',
    appId: '1:195208708595:ios:6af9f4441ad86883129286',
    messagingSenderId: '195208708595',
    projectId: 'appbook-1e0d2',
    databaseURL: 'https://appbook-1e0d2-default-rtdb.firebaseio.com',
    storageBucket: 'appbook-1e0d2.appspot.com',
    iosBundleId: 'com.example.appBook',
  );
}
